#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define CEDITOR "ceditor"
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 360
#define FONT_SIZE 20
#define TEXT_MARGIN 1.0f
#define BLINK_INTERVAL 0.5f
#define SIDEBAR_WIDTH 15
#define SIDEBAR_COLOR GRAY
#define SIDEBAR_MARGIN 2
#define CURSOR_UPDATE_INTERVAL 0.05f
#define KEY_DOWN_DELAY 0.5f
#define CURSOR_COLOR GRAY

#endif