#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define CEDITOR "ceditor"
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 360
#define FONT_SIZE 20
#define TEXT_MARGIN 1.0f
#define SIDEBAR_WIDTH 15
#define SIDEBAR_COLOR GRAY
#define SIDEBAR_MARGIN 2
#define KEY_DOWN_DELAY 0.5f
#define KEY_DOWN_INTERVAL 0.02f
#define BLINK_INTERVAL 0.5f
#define CURSOR_IDLE_INTERVAL 1.0f
#define BOTTOM_BAR_HEIGHT 20
#define BOTTOM_BAR_COLOR DARKGRAY
#define BOTTOM_BAR_FONT_SIZE 20
#define INPUT_BOX_WIDTH 200
#define INPUT_BOX_HEIGHT 20
#define DRAW_TEXT_SPACING 1.0f
#define HISTORY_LIMIT 20

#endif